.PHONY: clean

shell:  
	gcc -o shell shell.c
	gcc -o clear clear.c
	gcc -o cd cd.c
	gcc -o ls ls.c
	gcc -o clearls clearls.c
extras:
	g++ -std=c++11 -o  snake jsnake.cpp  -lncurses
	gcc -o shelly shelly.c
	gcc -o spoilers spoilers.c        
clean:
	rm shell
	rm clear
	rm cd
	rm ls
	rm clearls
	rm snake
	rm shelly

